### ISSUE TITLE
io.socket.engineio.client.EngineIOException: xhr poll error

### ISSUE THREAD

**Issue by noelbank00** [zsasko/laravel-echo-android-sample#2]
Hello! I create project following your instruction, and i have connection error:

![image](https://user-images.githubusercontent.com/63310862/204003212-9c5956d2-1bc6-4bd7-910d-8847796114e8.png)
![image](https://user-images.githubusercontent.com/63310862/204003177-001c0501-d882-4354-b407-63da612483f2.png)
![image](https://user-images.githubusercontent.com/63310862/204003250-011ad7ee-38d1-4784-ba45-d76d3737614e.png)

can u help resolve the problem?

**Comment by zsasko** [comment]
You have to add your domain in 'res/xml/network_security_config.xml' file:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
    </domain-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">automento.insource.hu</domain>
    </domain-config>
</network-security-config>
```

**Comment by noelbank00** [comment]
I use * for security_config... I thought that work same. Thank you.
